services:
  - type: web
    name: agri-saarthi-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    autoDeploy: true
    # envVars:
    #   - key: GOOGLE_APPLICATION_CREDENTIALS
    #     value: /etc/secrets/agrisaarthi-df25af480006.json
